api_key: Ro1oYXAR5xa5SDuPuWUokg0Xq
api_key_secret: CWeCDONZfak2CL0jLtjKWi8zSbCL7vShGU4E5WyCM7QLp0Sowc
bearer_token: AAAAAAAAAAAAAAAAAAAAANCebgEAAAAA%2Fv5Vu9%2BdnaU8SEJuKdfMj5Xt8J0%3Du1RS9P7JHqFm4d8iWnOo01Mf0kufKPl2K2XVbX2114ObLDZYvS
callback_uri: oob
access_token: 1515602516771500037-1fmMmi8kAFNKwGBWkwwcgEWJjZRbrc
access_token_secret: kGOsrnsL66o8shwiGyiv3f2vRWt0K19eQ0HpafuLqTxQn
